// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Way2DevBootcamp.Data.Context;

#nullable disable

namespace Way2DevBootcamp.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211230223034_SeedCategoria")]
    partial class SeedCategoria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Way2DevBootcamp.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Acessórios de Tecnologia"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ar e Ventilação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Artesanato"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Artigos para Festa"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Áudio"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Automotivo"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Bebês"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Beleza & Perfumaria"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Brinquedos"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Cama, Mesa e Banho"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Câmeras e Drones"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Casa e Construção"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Casa Inteligente"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Celular e Smartphone"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Colchões"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Comércio e Indústria"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Cursos"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Decoração"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Eletrodomésticos"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Eletroportáteis"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Esporte e Lazer"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Ferramentas"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Filmes e Séries"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Games"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Informática"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Instrumentos Musicais"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Livros"
                        },
                        new
                        {
                            Id = 28,
                            Nome = "Mercado"
                        },
                        new
                        {
                            Id = 29,
                            Nome = "Moda"
                        },
                        new
                        {
                            Id = 30,
                            Nome = "Móveis"
                        },
                        new
                        {
                            Id = 31,
                            Nome = "Música e Shows"
                        },
                        new
                        {
                            Id = 32,
                            Nome = "Natal"
                        },
                        new
                        {
                            Id = 33,
                            Nome = "Papelaria"
                        },
                        new
                        {
                            Id = 34,
                            Nome = "Pet Shop"
                        },
                        new
                        {
                            Id = 35,
                            Nome = "Relógios"
                        },
                        new
                        {
                            Id = 36,
                            Nome = "Saúde e Cuidados Pessoais"
                        },
                        new
                        {
                            Id = 37,
                            Nome = "Serviços"
                        },
                        new
                        {
                            Id = 38,
                            Nome = "Suplementos Alimentares"
                        },
                        new
                        {
                            Id = 39,
                            Nome = "Tablets, iPads e E - Readers"
                        },
                        new
                        {
                            Id = 40,
                            Nome = "Telefonia Fixa"
                        },
                        new
                        {
                            Id = 41,
                            Nome = "TV e Vídeo"
                        },
                        new
                        {
                            Id = 42,
                            Nome = "Utilidades Domésticas"
                        });
                });

            modelBuilder.Entity("Way2DevBootcamp.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("Way2DevBootcamp.Domain.Entities.Produto", b =>
                {
                    b.HasOne("Way2DevBootcamp.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Way2DevBootcamp.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
